baseURL = "https://dakotahpena.studio/"
languageCode = "en-us"
title = "Dakotah Peña"
sectionPagesMenu = "main"
publishDir = "docs"
copyright = "© Dakotah Peña"
enableGitInfo = true

[author]
  name = "Dakotah"
  email = "dakotah@hey.com"

[params]
  author = "Dakotah"
  contactEmail = "dakotah@hey.com"
  dateFormat = "Jan 2, 2006"
  description = "Dakotah Peña, maker."
  images = ["site-feature-image.jpg"]

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[taxonomies]
  category = "categories"
  tag = "tags"
